// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/3/2026, 10:26:11
const configMerger = require("C:/projects/dra-yissel-medico-internista/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/projects/dra-yissel-medico-internista/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/plugins/**/*.{js,ts,mjs}","C:/projects/dra-yissel-medico-internista/composables/**/*.{js,ts,mjs}","C:/projects/dra-yissel-medico-internista/utils/**/*.{js,ts,mjs}","C:/projects/dra-yissel-medico-internista/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/projects/dra-yissel-medico-internista/app.config.{js,ts,mjs}"] }));

module.exports = config
