// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/21/2026, 9:33:31 PM
const configMerger = require("/Users/lorenzoarellano/developer/dra-yissel/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.ts")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/lorenzoarellano/developer/dra-yissel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/plugins/**/*.{js,ts,mjs}","/Users/lorenzoarellano/developer/dra-yissel/composables/**/*.{js,ts,mjs}","/Users/lorenzoarellano/developer/dra-yissel/utils/**/*.{js,ts,mjs}","/Users/lorenzoarellano/developer/dra-yissel/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lorenzoarellano/developer/dra-yissel/app.config.{js,ts,mjs}"] }));

module.exports = config
